### ISSUE TITLE
Cannot load cfw via 3DSX on menuhax

### ISSUE THREAD

**Issue by Jerry-Shaw** [OperationNT414C/CtrBootManager#5] opened 2016-06-27 02:30 UTC
cakes, reinand, luma3ds, rxtools, all failed to load anyway on my new 3ds. But another CtrBootManager (Ver: 1.9 from gbatemp) works.

**Comment by OperationNT414C** [comment] 2016-06-27 07:19
Hello Jerry,

When you said "1.9", did you mean this one?
https://gbatemp.net/threads/ctrbootmanager-3ds-boot-manager-loader-homemenuhax.398383/

Do the "power off" feature works? (or do it display an error like "Err: khax..."?)

Thank you for your report.

**Comment by OperationNT414C** [comment] 2016-06-27 20:02
I try to get back the original 1.9 source code and compile it with my compilation process.
It seems that my compiled version is 4KB less than the one Cpasjuste provided on gbatemp.
I also notice that I don't have the latest khax version code. Can you please check if one of those version works?

[OriginalCode.zip](https://github.com/OperationNT414C/CtrBootManager/files/335737/OriginalCode.zip)

Thank you for your help!

Anyway, I probably did something wrong somewhere: the version 2.1.0 has more features than the 1.9 but the final binary is smaller...

EDIT: The size difference is probably due to the fact that version 1.9 uses "libconfig" with JSON parser, new version 2.1.0 uses INI parsing to read "boot.cfg" which is probably simpler.

**Comment by Jerry-Shaw** [comment] 2016-06-28 00:28
Yes, that is the one I am using now, all menu section works except the "HomeMenu" section. "power off" now named "ShutDown" also works fine. It can lead to any of the CFW, while version 2.1.0 does not. When I used version 2.1.0 last time, all other sections worked, but I could only load CFW though HBL.

I'll try the OriginalCode later when after work and report you of the details.

Haha, I, personally, like the "INI" style configure.

**Comment by Jerry-Shaw** [comment] 2016-06-28 00:35
BTW, which .cfg file should I use with the OriginalCode? INI style or JSON style?

**Comment by Jerry-Shaw** [comment] 2016-06-28 06:31
@OperationNT414C OK, I've tested the OriginalCode on my New 3DS, all works fine except the "HomeMenu" section. Just as the one I am using now (https://gbatemp.net/threads/ctrbootmanager-3ds-boot-manager-loader-homemenuhax.398383/), and seems like it is a little bit faster?

**Comment by OperationNT414C** [comment] 2016-06-28 06:44
Ok, thank you for your test!
This result means that it is not a compilation process issue, so I will probably be able to fix my version :-).
The fact that it look "faster" is strange: it should be the original version.
I try to put the INI config in 1.9. Can you tell me if this version still works for you ?

[CtrBootManager_1.9_INI.zip](https://github.com/OperationNT414C/CtrBootManager/files/336393/CtrBootManager_1.9_INI.zip)

It will probably take me some time to put back my New3DS in a state which allow to test your scenario. Before, I had the exact same configuration (MenuHax on 9.2 which boots CtrBootManager where I choose Luma3DS). But now, I am on A9LH. I still have my 9.2 SysNAND dump so I will try to put it back when I have some time, I just hope that I can still keep A9LH and boot my SysNAND with MenuHax to reproduce the issue.

**Comment by Jerry-Shaw** [comment] 2016-06-28 07:15
It should be OK if I have time to test, haha, and yes, the CtrBootManager_1.9_INI works.

**Comment by OperationNT414C** [comment] 2016-06-28 07:26
Thnak you for your time and your tests :-)
If the last version I send you works, it is a good start (it has INI style config and the last binary loader code).
Now, I am at work so I cannot generate new binaries. I will try to create tonight multiple versions where I put more code from the 2.1.0 version. It will allow me to detect which precise part causes the issue.

**Comment by Jerry-Shaw** [comment] 2016-06-28 07:38
emm... yep, debugging always costs time. I need to debug my PHP scripts too. If help is needed, leave me a message. Glad to test.

**Comment by OperationNT414C** [comment] 2016-06-28 17:42
I spend some time putting back my MenuHax environment (and keep my A9LH environment too at the same time).
I am able to reproduce the issue myself, I will try to see what part of the code causes the issue.
Thank you for your help!

**Comment by OperationNT414C** [comment] 2016-06-28 21:30
I looked at "gfx.h/gfx.c" in A9LH solution and I though it can be very confusing for 3DSX version compilation (this file doesn't exist in 1.9 project) because this header also exists in 3DS homebrew API. So I renamed it to "draw.h/draw.c" and I removed all "gfx" prefix on functions. When I compile it and I test the final version, I was able to start a CFW with it from MenuHax, I tested ReiNAND and Cakes with success, Luma3DS seems to fail. Can you please tell me if this version corrects the issue for you too? 
[CtrBootManager2.1_FixCFWBoot.zip](https://github.com/OperationNT414C/CtrBootManager/files/338088/CtrBootManager2.1_FixCFWBoot.zip)

Can you also test Luma3DS? I supect it to crash due to my scenario for reproduction:
- A9LH boot using Luma3DS "arm9loaderhax.bin"
- Luma3DS boots on SysNAND 9.2 which is configurated with MenuHax (I use "LessHax" payload which is more stable than default MenuHax payload)
- MenuHax starts "less.3dsx" which is CtrBootManager
- Start a CFW from CtrBootManager

So there is a Luma3DS "loop" in my process.

**Comment by Jerry-Shaw** [comment] 2016-06-29 00:39
@OperationNT414C Morning. 

I just tested the new 2.1 with FixCFWBoot, all works fine. 

I didn't have the issue with Luma3DS (the latest nightly version), it starts normally just as Cakes. I tested Cakes, ReiNAND, Luma3DS, and even the last one of rxTools, all good. 

The only thing is that, ReiNAND failed to load for 2 out of 5, which I thought would be the problem of ReiNAND itself, as it DID when I was using the Ver 1.9. Others are loaded with 100% success (5 times' test).

I am not using "LessHax" payload, but the "NinjaHax 2.7" without debug screen version under MenuHax 2.2 (I forgot the URL, it should almost be the same with the MenuHax's default payload). Some stuff under HBL will must failed under "LessHax" like CTRXplorer, FBI, etc... They report an error of CPU incorrect, which made me give it up.

So, accordingly, the one you give to me fix all the load issues. Not using A9, sorry for that, cannot help to test it under A9. Used to brick one when doing A9, so I stay on menuhax. SyaNAND 9.2.0-20J, MenuHax 2.2, NinjaHax 2.7 without debug screen payload, all CFW are up to the nightly latest one, and all passed.

You can change the payload and test it again and download the latest nightly version of Luma3DS and make another test, I am not sure which goes wrong.

And, thanks so much for fixing the issue.

**Comment by Jerry-Shaw** [comment] 2016-06-29 03:29
BTW, how does the "autobootfix" affect? Should I change it to "2" as I am using New 3DS?

**Comment by OperationNT414C** [comment] 2016-06-29 07:56
"autobootfix" was initialy created when you use a timeout of 0 with a recovery key: CtrBootManager automatically starts its default selection if the recovery key is not maintained. Due to MenuHax instabilities, it has been noticed that if the chainloading is "too quick", it crashes. So "autobootfix" forces to wait some frames before automatic chainloading.

I already checked the A9LH version, it was unaffected by my draw functions refactoring (the final binary size is exactly the same as before).

So, I will create a new official CtrBootManager version with this fix. Thank you for your report and your help!

**Comment by Jerry-Shaw** [comment] 2016-06-29 10:38
My pleasure to help, haha, wait for the final one.

**Comment by OperationNT414C** [comment] 2016-06-29 16:36
Here is the official fix for the issue:
https://github.com/OperationNT414C/CtrBootManager/releases/tag/2.1.1

Thank you again for your help, I think I can close this issue.

**Closed as completed** 2016-06-29 16:37 UTC
Labels: bug

**Comment by Jerry-Shaw** [comment] 2016-06-29 23:59
Yep, good job. Thank you for the new version of CtrBootManager, haha.
